const colors = [
  {
    id: 'phthaloBlue',
    name: 'Phthalo Blue',
    pigment: 'Copper Pthalocyanine',
    swatch: 'assets/colorimages/phthaloblue.jpg',
    colorgroupId: 'blue',
  },
  {
    id: 'ultramarineBlue',
    name: 'Ultramarine Blue',
    pigment: 'Polysulphide of Sodium-Alumnio-Silicate',
    swatch: 'assets/colorimages/ultramarine.jpg',
    colorgroupId: 'blue',
  },
  {
    id: 'vermillion',
    name: 'Vermillion',
    pigment: 'Cadmium (Sulpho-Selenide)',
    swatch: 'assets/colorimages/vermillion.jpg',
    colorgroupId: 'red',
  },
  {
    id: 'cadmiumRedMed',
    name: 'Cadmium Red Medium',
    pigment: 'Cadmium (Sulpho-Selenide)',
    swatch: 'assets/colorimages/cadredmed.jpg',
    colorgroupId: 'red',
  },
  {
    id: 'purpleMadder',
    name: 'Purple Madder',
    pigment: 'Monoazo, Carbonized Bones',
    swatch: 'assets/colorimages/purplemadder.jpg',
    colorgroupId: 'violet',
  },
  {
    id: 'quinacridoneMagenta',
    name: 'Quinacridone Magenta',
    pigment: 'Quinacridone',
    swatch: 'assets/colorimages/quinacrodone.jpg',
    colorgroupId: 'violet',
  },
  {
    id: 'cobaltViolet',
    name: 'Cobalt Violet',
    pigment: 'Cobalt Phosphate',
    swatch: 'assets/colorimages/cobaltviolet.jpg',
    colorgroupId: 'violet',
  },
  {
    id: 'burntUmber',
    name: 'Burnt Umber',
    pigment: 'Synthetic Iron Oxide',
    swatch: 'assets/colorimages/burntumber.jpg',
    colorgroupId: 'earth',
  },
  {
    id: 'yellowOchre',
    name: 'Yellow Ochre',
    pigment: 'Synthetic Iron Oxide',
    swatch: 'assets/colorimages/yellowochre.jpg',
    colorgroupId: 'earth',
  },
  {
    id: 'phthaloGreen',
    name: 'Phthalo Green',
    pigment: 'Polychloro Copper Pthalocyanine',
    swatch: 'assets/colorimages/phthalogreen.jpg',
    colorgroupId: 'green',
  },
  {
    id: 'viridian',
    name: 'Viridian',
    pigment: 'Hydrous Chromic Oxide',
    swatch: 'assets/colorimages/viridian.jpg',
    colorgroupId: 'green',
  },
  {
    id: 'sapGreen',
    name: 'Sap Green',
    pigment: 'Arylide, Cobalt Titinate Spinel',
    swatch: 'assets/colorimages/sapgreen.jpg',
    colorgroupId: 'green',
  },
  {
    id: 'cadmiumYellowMed',
    name: 'Cadmium Yellow Medium',
    pigment: 'Cadmium Sulphide',
    swatch: 'assets/colorimages/cadyellow.jpg',
    colorgroupId: 'yellow',
  },
  {
    id: 'naplesYellow',
    name: 'Naples Yellow',
    pigment: 'Mixed Metal Oxide',
    swatch: 'assets/colorimages/naples.jpg',
    colorgroupId: 'yellow',
  },
  {
    id: 'flakeWhite',
    name: 'Flake White',
    pigment: 'Basic Lead Carbonate, Titanium Dioxide',
    swatch: 'assets/colorimages/flakewhite.jpg',
    colorgroupId: 'white',
  },
  {
    id: 'titaniumWhite',
    name: 'Titanium White',
    pigment: 'Titanium Dioxide',
    swatch: 'assets/colorimages/titaniumwhite.jpg',
    colorgroupId: 'white',
  },
];

module.exports = { colors };
